# Generated by Django 5.1.1 on 2024-10-14 13:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["position"]},
        ),
        migrations.AlterField(
            model_name="place",
            name="detail_description",
            field=tinymce.models.HTMLField(
                blank=True,
                verbose_name="Detailed description",
            ),
        ),
    ]
